
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  modulesSidebar: [
    {
      type: 'category',
      label: '🤖 Module 1: ROS 2 System',
      link: { type: 'doc', id: 'modules/module1' },
      items: [
        { type: 'link', label: 'Introduction', href: '/docs/modules/module1#introduction' },
        { type: 'link', label: 'ROS 2 Architecture', href: '/docs/modules/module1#ros-2-architecture--dds' },
        { type: 'link', label: 'Nodes & Lifecycle', href: '/docs/modules/module1#nodes--lifecycle-management' },
        { type: 'link', label: 'Topics & Pub/Sub', href: '/docs/modules/module1#topics-publishers--subscribers' },
        { type: 'link', label: 'Services & Actions', href: '/docs/modules/module1#services--actions' },
        { type: 'link', label: 'URDF & Robot Description', href: '/docs/modules/module1#urdf--robot-description' },
        { type: 'link', label: 'Launch Files', href: '/docs/modules/module1#launch-files' },
        { type: 'link', label: 'Project: Multi-Node', href: '/docs/modules/module1#project-multi-node-system' },
      ],
    },
    {
      type: 'category',
      label: '🎮 Module 2: Digital Twin',
      link: { type: 'doc', id: 'modules/module2' },
      items: [
        { type: 'link', label: 'Introduction', href: '/docs/modules/module2#introduction' },
        { type: 'link', label: 'Physics & Worlds', href: '/docs/modules/module2#physics-engines--world-building' },
        { type: 'link', label: 'Sensor Modeling', href: '/docs/modules/module2#sensor-modeling' },
        { type: 'link', label: 'Sim-to-Real', href: '/docs/modules/module2#sim-to-real--domain-randomization' },
        { type: 'link', label: 'Project: Gazebo Sim', href: '/docs/modules/module2#project-gazebo-simulation' },
      ],
    },
    {
      type: 'category',
      label: '🧠 Module 3: AI Brain',
      link: { type: 'doc', id: 'modules/module3' },
      items: [
        { type: 'link', label: 'Introduction', href: '/docs/modules/module3#introduction' },
        { type: 'link', label: 'Omniverse & USD', href: '/docs/modules/module3#nvidia-omniverse--usd' },
        { type: 'link', label: 'Synthetic Data', href: '/docs/modules/module3#synthetic-data-generation-sdg' },
        { type: 'link', label: 'HW Acceleration', href: '/docs/modules/module3#hardware-acceleration-with-isaac-ros' },
        { type: 'link', label: 'VSLAM Pipeline', href: '/docs/modules/module3#vslam--perception-pipelines' },
        { type: 'link', label: 'Project: Isaac Pipeline', href: '/docs/modules/module3#project-isaac-perception-pipeline' },
      ],
    },
    {
      type: 'category',
      label: '👁️ Module 4: VLA',
      link: { type: 'doc', id: 'modules/module4' },
      items: [
        { type: 'link', label: 'Introduction', href: '/docs/modules/module4#introduction' },
        { type: 'link', label: 'VLA Fundamentals', href: '/docs/modules/module4#vla-fundamentals' },
        { type: 'link', label: 'Voice Interface', href: '/docs/modules/module4#voice-interface-whisper' },
        { type: 'link', label: 'Cognitive Planning', href: '/docs/modules/module4#cognitive-planning-llms' },
        { type: 'link', label: 'Capstone Project', href: '/docs/modules/module4#capstone-project' },
      ],
    },
  ],
  hardwareSidebar: [
    {
      type: 'category',
      label: '🎮 Hardware Specs',
      link: {
        type: 'generated-index',
      },
      items: [{ type: 'autogenerated', dirName: 'hardware' }],
    },
  ],
  deploymentSidebar: [
    {
      type: 'category',
      label: '🚀 Deployment Guide',
      link: {
        type: 'generated-index',
      },
      items: [{ type: 'autogenerated', dirName: 'deployment' }],
    },
  ],
  tutorialSidebar: [
    {
      type: 'category',
      label: '📚 Tutorials',
      link: {
        type: 'generated-index',
      },
      items: [{ type: 'autogenerated', dirName: 'tutorials' }],
    },
  ],
};

export default sidebars;
